# NumPy Tutorial in Jupyter

This notebook demonstrates the core features of **NumPy**, a Python library for numerical computing. We'll cover:
- Creating and manipulating arrays
- Performing array operations (element-wise, broadcasting)
- Linear algebra operations (matrix multiplication, solving equations)
- Generating random numbers

Run each code cell with `Shift + Enter` to see the output. Ensure NumPy is installed (`pip install numpy`).

## 1. Installing and Importing NumPy

In [2]:
# Install NumPy (uncomment if needed)
# !pip install numpy
# py -m pip install numpy


# Import NumPy
import numpy as np

## 2. Creating and Manipulating Arrays

NumPy's core object is the `ndarray`, 
a multi-dimensional array for efficient data storage and manipulation.

In [6]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# Create a 2D array (matrix)
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print("\n2D Array:\n", arr2)

# Create arrays with special values
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 2))   # 3x2 array of ones
range_arr = np.arange(0, 10, 2)  # Array from 0 to 8, step 2
linspace_arr = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nArange:", range_arr)
print("\nLinspace:", linspace_arr)

1D Array: [1 2 3 4]

2D Array:
 [[1 2]
 [3 4]
 [5 6]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Arange: [0 2 4 6 8]

Linspace: [0.00000000e+00 9.00090009e-05 1.80018002e-04 ... 9.99819982e-01
 9.99909991e-01 1.00000000e+00]


In [7]:
# Array properties
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)  # (rows, columns)
print("Size:", arr.size)   # Total number of elements
print("Data type:", arr.dtype)  # Data type of elements

# Indexing and slicing
print("\nFirst row:", arr[0])
print("Element at [1, 2]:", arr[1, 2])  # Row 1, column 2
print("First column:\n", arr[:, 0])  # All rows, column 0

Shape: (2, 3)
Size: 6
Data type: int64

First row: [1 2 3]
Element at [1, 2]: 6
First column:
 [1 4]


## 3. Array Operations

NumPy supports element-wise operations, broadcasting, and aggregations.

In [8]:
# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)

# Broadcasting: Add scalar to array
print("Add 10 to all elements:", a + 10)

# Universal functions (ufuncs)
print("Sine of a:", np.sin(a))
print("Sum of a:", np.sum(a))
print("Mean of a:", np.mean(a))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square: [1 4 9]
Add 10 to all elements: [11 12 13]
Sine of a: [0.84147098 0.90929743 0.14112001]
Sum of a: 6
Mean of a: 2.0


## 4. Linear Algebra

NumPy's `linalg` module provides tools for matrix operations, solving equations, and more.

In [8]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matmul = np.matmul(A, B)
dot = A @ B  # Alternative syntax
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix multiplication (A @ B):\n", dot)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]


In [9]:
# Solving a system of linear equations
# 2x + y = 5
# x + 3y = 10
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 10])

x = np.linalg.solve(A, b)
print("Solution (x, y):", x)
print("Verification (A @ x):", A @ x)

Solution (x, y): [1. 3.]
Verification (A @ x): [ 5. 10.]


In [10]:
# Determinants and inverses
det = np.linalg.det(A)
print("Determinant of A:", det)

inv_A = np.linalg.inv(A)
print("\nInverse of A:\n", inv_A)

identity = A @ inv_A
print("\nA @ A_inv (should be identity):\n", identity)

Determinant of A: 5.000000000000001

Inverse of A:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

A @ A_inv (should be identity):
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


## 5. Random Number Generation

NumPy's `random` module is useful for simulations and testing.

In [11]:
# Set seed for reproducibility
np.random.seed(47)

# Random integers between 1 and 10
rand_ints = np.random.randint(1, 11, size=(2, 3))
print("Random integers (2x3):\n", rand_ints)

# Random floats from normal distribution
rand_norm = np.random.normal(loc=0, scale=1, size=(2, 2))
print("\nRandom normal (2x2):\n", rand_norm)

Random integers (2x3):
 [[8 7 8]
 [9 9 4]]

Random normal (2x2):
 [[ 1.33368001 -0.95418842]
 [ 0.55702381  1.14650159]]


## 6. Next Steps

- Try modifying array shapes or operations.
- Explore advanced NumPy functions (e.g., `np.fft`, `np.where`).
- Combine with Matplotlib for visualizations (add `%matplotlib inline`).

For more, check the [NumPy documentation](https://numpy.org/doc/stable/).